FROM python:3.12.10-slim-bookworm

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY proto/agent.proto proto/agent.proto
COPY python-server/server.py server.py
RUN python -m grpc_tools.protoc -Iproto --python_out=. --grpc_python_out=. proto/agent.proto
RUN useradd --create-home --uid 10001 spike

USER spike
CMD ["python", "server.py"]
