FROM python:3.12.10-slim-bookworm

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY python-backend python-backend
RUN useradd --create-home --uid 10001 spike

USER spike
CMD ["uvicorn", "python-backend.streaming_server:app", "--host", "0.0.0.0", "--port", "8000"]
